name: Test

on: push

jobs:
  ESlint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install dependencies
      run: npm install
    - name: ESlint
      run: npm run lint
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install dependencies
      run: npm install
    - name: Jest
      run: npm run test
